In [15]:
#importar biblioteca com nome especifico
import numpy as np

#formar linhas de matrizes
a = np.array(['a', 'b', 'c'])
print(a)

b = np.array([1, 2 ,3])
print(b)

#formar matrizes 3x3
c= np.array([(4, 5, 6), (7, 8, 9), (10, 11, 12)])
print(c)

#formar matrizes de zeros 3x4
d = np.zeros((3,4))
print(d)

#formar matrizes de um 3x4
e = np.ones((3,4))
print(e)

#formar matrizes com diagonal de 1, ela ja calcula o numero de colunas, vc so da o numero de linhas.
f = np.eye(4)
print(f)

['a' 'b' 'c']
[1 2 3]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#operações com valores em matrizes

c.sum()
#operações de soma com os valores da matriz c

c.mean()
#operações de média com os valores da matriz c

c.std()
#calculo do desvio padrao com os valores da matriz c

2.581988897471611